MENU_ITEMS =[
    {'href': '/componist/',
     'label': 'Componist',
     },
    {'href': '/performer/',
     'label': 'Performer',
     },
    {'href': '/pianoboek/',
     'label': 'Pianoboek',
     },
    {'href': '/collection/',
     'label': 'Collectie',
     },
    {'href': '/gather/',
     'label': 'Verzamelalbum',
     },
    {'href': '/tag/',
     'label': 'Tags',
     },
    {'href': '/extra/',
     'label': 'Extra',
     },
    {'href': '/search/',
     'label': 'Zoek',
     },
    {'href': '/upload/',
     'label': 'Upload',
     },
]


